services:
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    container_name: kafka
    ports:
      - ${KAFKA_PORT_EX}
      - ${KAFKA_PORT_IN}
    environment:
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}

      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_SECURITY_PROTOCOL}
      
      KAFKA_NODE_ID: ${KAFKA_NODE}
      KAFKA_PROCESS_ROLES: ${KAFKA_ROLE}
      KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_NAMES}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_VOTERS}

      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_BROKER_LISTENER_NAME}

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSET_TOPIC}
    volumes:
      - ./KAFKA/data:${KAFKA_PATH}
    networks:
      - backend

  kafka-ui:
    image: kafbat/kafka-ui:main
    container_name: kafka-ui
    ports:
      - ${KAFKAUI_PORT}
    environment:
      DYNAMIC_CONFIG_ENABLED: ${KAFKAUI_DYNAMIC_CONFIG}
      KAFKA_CLUSTERS_0_NAME: ${KAFKAUI_CLUSTER_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKAUI_CONNECT}
    depends_on:
      - kafka
    networks:
      - backend

networks:
  backend:
    external: true
