services:
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    container_name: kafka
    ports:
      - ${KAFKA_PORT}
    enviroment:
      KAFKA_NODE_ID: ${KAFKA_NODE}
      KAFKA_BROKER_ID: ${KAFKA_BROKER}
      KAFKA_PROCESS_ROLES: ${KAFKA_ROLE}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_VOTERS}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_SECUTIRY_PROTOCOL}
      KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_NAMES}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_BROKER_LISTENER_NAME}
      CLUSTER_ID: ${KAFKA_CLUSTER}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSET_TOPIC}
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: ${KAFKA_GROUP_INITIAL}
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${KAFKA_DEFAULT_REPLICATION}
      KAFKA_MIN_INSYNC_REPLICAS: ${KAFKA_MIN_REPLICAS}
    volumes:
      - kafka_data:${KAFKA_PATH}
    networks:
      - ${DOCKER_NETWORK}

networks:
  ${DOCKER_NETWORK}:
    driver: bridge

volumes:
  kafka_data:
