services:
  service-file:
    container_name: service-file
    build:
      context: ../service-file
    depends_on:
      - eureka
      - kafka
    networks:
      - backend
  
  service-product:
    container_name: service-product
    build:
      context: ../service-product
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB_PRODUCT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - OPENAPI_NAME=${OPENAPI_NAME_PRODUCT}
      - OPENAPI_VERSION=${OPENAPI_VERSION_PRODUCT}
      - OPENAPI_SOURCE=${OPENAPI_SOURCE}
      - SPRINGDOC_APIDOCS=${SPRINGDOC_APIDOCS}
      - SPRINGDOC_SWAGGER_UI=${SPRINGDOC_SWAGGER_UI}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - EUREKA_NAME=${EUREKA_NAME}
      - EUREKA_PORT=${EUREKA_PORT_EX}
      - KAFKA_SERVER=${KAFKA_SERVER}
    depends_on:
      - eureka
      - db
      - kafka
    networks:
      - backend

  service-user:
    container_name: service-user
    build:
      context: ../service-user
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB_USER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - OPENAPI_NAME=${OPENAPI_NAME_USER}
      - OPENAPI_VERSION=${OPENAPI_VERSION_USER}
      - OPENAPI_SOURCE=${OPENAPI_SOURCE}
      - SPRINGDOC_APIDOCS=${SPRINGDOC_APIDOCS}
      - SPRINGDOC_SWAGGER_UI=${SPRINGDOC_SWAGGER_UI}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - EUREKA_NAME=${EUREKA_NAME}
      - EUREKA_PORT=${EUREKA_PORT_EX}
      - KAFKA_SERVER=${KAFKA_SERVER}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
    depends_on:
      - eureka
      - db
      - kafka
    networks:
      - backend
  
  service-mail:
    container_name: service-mail
    build:
      context: ../service-mail
    depends_on:
      - kafka
    environment:
      - OPENAPI_NAME=${OPENAPI_NAME_MAIL}
      - OPENAPI_VERSION=${OPENAPI_VERSION_MAIL}
      - OPENAPI_SOURCE=${OPENAPI_SOURCE}
      - SPRINGDOC_APIDOCS=${SPRINGDOC_APIDOCS}
      - SPRINGDOC_SWAGGER_UI=${SPRINGDOC_SWAGGER_UI}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - EUREKA_NAME=${EUREKA_NAME}
      - EUREKA_PORT=${EUREKA_PORT_EX}
      - KAFKA_SERVER=${KAFKA_SERVER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - backend
  
networks:
  backend:
    external: true