services:
  service-file:
    container_name: service-file
    build:
      context: ../service-file
    env_file:
      - ../service-file/file_service/.env.prod
    depends_on:
      - eureka
    networks:
      - backend
  
  service-product:
    container_name: service-product
    build:
      context: ../service-product  
    environment:
      - DB_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=products_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - OPENAPI_NAME=product-service doc
      - OPENAPI_VERSION=1.0.0
      - OPENAPI_SOURCE=localhost:8080
      - SPRINGDOC_APIDOCS=/v3/api-docs
      - SPRINGDOC_SWAGGER_UI=/swagger-ui.html
      - EUREKA_SERVER=server-eureka
      - EUREKA=eureka
      - EUREKA_PORT=8761
      - KAFKA_SERVER=kafka:29092
    depends_on:
      - eureka
      - db
    networks:
      - backend

  service-user:
    container_name: service-user
    build:
      context: ../service-user  
    environment:
      - DB_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=users_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - OPENAPI_NAME=service-user doc
      - OPENAPI_VERSION=1.0.0
      - OPENAPI_SOURCE=localhost:8080
      - SPRINGDOC_APIDOCS=/v3/api-docs
      - SPRINGDOC_SWAGGER_UI=/swagger-ui.html
      - EUREKA_SERVER=server-eureka
      - EUREKA=eureka
      - EUREKA_PORT=8761
      - KAFKA_SERVER=kafka:29092
      - JWT_SECRET=key
      - JWT_ISSUER=issuer
    depends_on:
      - eureka
      - db
    networks:
      - backend
  

networks:
  backend:

