services:
  eureka:
    build:
      context: ../eureka
    container_name: server-eureka
    env_file:
      - .env
    ports:
      - ${EUREKA_PORT}
    networks:
      - backend
    restart: always

networks:
  backend:
    external: true
