services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}
    enviroment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:${POSTGRES_PATH}
    networks:
      - ${DOCKER_NETWORK}

networks:
  ${DOCKER_NETWORK}:
    driver: bridge

volumes:
  postgres_data:
