services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:${POSTGRES_PATH}
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  postgres_data:
