services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:${POSTGRES_PATH}
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  postgres_data:
