services:
  gateway:
    build:
      context: ../gateway
    container_name: service-gateway
    environment:
      EUREKA_SERVER: ${EUREKA_SERVER}
      EUREKA_NAME: ${EUREKA_NAME}
      EUREKA_PORT: ${EUREKA_PORT_EX}
    ports:
      - ${GATEWAY_PORT}
    depends_on:
      - eureka
    networks:
      - backend    
    restart: always

networks:
  backend:
    external: true
